import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { cn } from '@/shared/utils';

import { Providers } from './providers';

import './styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang='en' suppressHydrationWarning>
    <body className={cn('min-h-screen', inter.className)}>
      <Providers>{children}</Providers>
    </body>
  </html>
);

export default RootLayout;
