import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';

import { ThemeProvider } from '@/app/providers';
import { Toaster } from '@/shared/ui';
import { cn } from '@/shared/utils';

import '@/app/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en" suppressHydrationWarning>
    <body className={cn('min-h-screen', inter.className)}>
      <ThemeProvider>{children}</ThemeProvider>
      <Toaster />
    </body>
  </html>
);

export default RootLayout;
